### ISSUE TITLE
2FA Email funktioniert nicht

### ISSUE THREAD

**Issue by FrodoVDR** [Grizzelbee/ioBroker.dysonairpurifier#103]
Ich habe den Button mit Firefox, Chrome und Edge unter Windows 10 versucht zu betätigen, das einzige was ich sehe ist ein Farbwechsel des Buttons beim überqueren mit dem Mauszeiger. Bei drücken passiert nichts.

Leider funktioniert bei mir seit gestern auch der Trick mit der geöffneten App nicht mehr. Die beim gestern einen Update.
Ich habes es gerade nocheinmal versucht jetzt funktioniert es mit geöffneter App wieder.

**Comment by Grizzelbee** [comment]
Bitte stell mir ein Debug-Log des Anmeldeversuchs zur Verfügung.
Und guck bitte mal ins Konsolenlog (F12 drücken) der Config-Seite beim Anmeldeversuch ob da etwas steht.

**Comment by FrodoVDR** [comment]
Im Browser steht nur folgendes:
```
Given parameters: email:[meine@email.com], pwd:[passwort], country:[de], index_m.html:82:21
Send 2fa query to dyson cloud API ... index_m.html:86:21

Passwort-Felder sind in einem unsicheren (http://) Iframe vorhanden. Dies ist ein Sicherheitsrisiko, durch das Zugangsdaten gestohlen werden können.index_m.html
```
Das iobroker debug Log behauptet mein Benutzer un Passwort wäre falsch:
`2021-05-14 21:20:15.706  - info: dysonairpurifier.0 (3318346) starting. Version 0.8.2 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v12.22.1, js-controller: 3.2.16
2021-05-14 21:20:15.737  - info: dysonairpurifier.0 (3318346) Signing in into dyson cloud API ...
2021-05-14 21:20:16.148  - info: dysonairpurifier.0 (3318346) Result from API-Status request -> Account is: ACTIVE
2021-05-14 21:20:16.635  - error: dysonairpurifier.0 (3318346) Error during dyson cloud API login:Error: Request failed with status code 401, Callstack: Error: Request failed with status code 401
    at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-05-14 21:20:16.636  - error: dysonairpurifier.0 (3318346) Error: Unable to authenticate user! Your credentials seem to be invalid. Please double check and fix them.
2021-05-14 21:20:16.636  - error: dysonairpurifier.0 (3318346) Credentials used for login: User:[meine@email.com] - Password:[passwort] - Country:[de]
2021-05-14 21:20:16.637  - error: dysonairpurifier.0 (3318346) [main()] error: undefined, stack: undefined
`

**Comment by Grizzelbee** [comment]
Hmm. MDu hast einen komischen Versions-Mischmasch:

>2021-05-14 21:20:15.706  - info: dysonairpurifier.0 (3318346) starting. Version 0.8.2

Da sollte 0.9.0 stehen. Bitte installiere noch einmal sauber von Github neu.

**Comment by FrodoVDR** [comment]
Ich habe es nun komplett alles entfernt und kann es nun nicht mehr installieren:
```
$ ./iobroker url "https://github.com/Grizzelbee/ioBroker.dysonairpurifier.git" --debug
install Grizzelbee/ioBroker.dysonairpurifier#4143f9868a6fc612a6529d6617aa29f47fbbfbe9
NPM version: 6.14.12
npm install Grizzelbee/ioBroker.dysonairpurifier#4143f9868a6fc612a6529d6617aa29f47fbbfbe9 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2021-05-14T20_34_40_734Z-debug.log
ERROR: host.iobroker1 Cannot install Grizzelbee/ioBroker.dysonairpurifier#4143f9868a6fc612a6529d6617aa29f47fbbfbe9: 1
ERROR: process exited with code 25
```

**Comment by FrodoVDR** [comment]
Ich habe die Fehlerhafte Codeziele wie folgt geändert, damit startet der Adapter allerdings bekomme ich nach wie vor keine Email.
```
                // TP02: When continuous monitoring is off and the fan ist switched off - temperature and humidity loose their values.
                // test whether the values are invalid and config.keepValues is true to prevent the old values from beeing destroyed
                if ( message[deviceConfig[0]] === 'OFF' && adapter.config.keepValues ) {
                    continue;
                };
```

```
2021-05-15 11:25:12.156  - info: dysonairpurifier.0 (1196468) starting. Version 0.9.0 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v12.22.1, js-controller: 3.2.16
2021-05-15 11:25:12.181  - info: dysonairpurifier.0 (1196468) Querying devices from dyson API.
2021-05-15 11:25:12.441  - error: dysonairpurifier.0 (1196468) [main()] error: undefined, stack: undefined
```

**Comment by Grizzelbee** [comment]
Ich habe gerade versucht meine "Produktionsumgebung" direkt von Git zu aktualisieren und das hat nicht funktioniert. Der Broker hat nichts herunter geladen oder installiert.
Daraufhin habe ich das Release mit npm etc. vervollständigt und es lässt sich nicht nur installieren - 2fa läuft auch auf Anhieb auf meiner Linux-Prod.
Also: Bitte jetzt mit dem fertigen release noch einmal installieren und testen.

**Comment by Grizzelbee** [comment]
Lt. NPM haben mindestens 74 von 87 Usern die 0.9.0 installiert und ich habe keine Klagen gehört. Der Issue scheint also gelöst.
