### ISSUE TITLE
2FA Anmeldung geht nicht

### ISSUE THREAD

**Issue by ManuW19** [Grizzelbee/ioBroker.dysonairpurifier#124]
Bei mir funktioniert die 2FA Anmeldung immer noch nicht. Mehrmalige Neuinstallation des Adapters hat nix geholfen.

Betriebssystem des Brokers:Linux
Versionen von js-controller:3.2.16
Admin:5.1.23
Node:14.17.4
dyson-Adapter:0.9.2
Debug-Log vom Broker komplett vom Start des Adapters bis zum Fehler:

dysonairpurifier.0 | 2021-08-17 12:50:17.329 | error | getDyson2faMailError: Request failed with status code 401
-- | -- | -- | --
dysonairpurifier.0 | 2021-08-17 12:50:02.630 | error | [main()] error: undefined, stack: undefined
dysonairpurifier.0 | 2021-08-17 12:50:02.224 | info | Querying devices from dyson API.
dysonairpurifier.0 | 2021-08-17 12:50:02.118 | info | starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v14.17.4, js-controller: 3.2.16
dysonairpurifier.0 | 2021-08-17 12:49:41.363 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
dysonairpurifier.0 | 2021-08-17 12:49:41.360 | info | terminating
dysonairpurifier.0 | 2021-08-17 12:49:41.356 | info | Cleaned up everything...
dysonairpurifier.0 | 2021-08-17 12:49:41.354 | info | Got terminate signal TERMINATE_YOURSELF

, Konsolen Log des Browsers, das den Fehler im Admin anzeigt:

host.homebridge | 2021-08-17 12:49:58.882 | info | instance system.adapter.dysonairpurifier.0 started with pid 2811
-- | -- | -- | --
host.homebridge | 2021-08-17 12:49:58.707 | info | "system.adapter.dysonairpurifier.0" enabled
host.homebridge | 2021-08-17 12:49:41.957 | info | instance system.adapter.dysonairpurifier.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.homebridge | 2021-08-17 12:49:41.356 | info | stopInstance system.adapter.dysonairpurifier.0 send kill signal
host.homebridge | 2021-08-17 12:49:41.264 | info | stopInstance system.adapter.dysonairpurifier.0 (force=false, process=true)
host.homebridge | 2021-08-17 12:49:41.241 | info | "system.adapter.dysonairpurifier.0" disabled

Ich hoffe das sind ausreichend Informationen. Habe mich an die Infos im Readme gehalten und Anmeldedaten bei Dyson sind auch richtig

**Comment by kkickingereder** [comment]
Auch bei mir mit aktualisierten Adapter, keine Change



dysonairpurifier.0 | 2021-08-17 15:10:03.454 | error | getDyson2faMailError: Request failed with status code 401
-- | -- | -- | --
dysonairpurifier.0 | 2021-08-17 15:09:53.391 | error | [main()] error: undefined, stack: undefined
dysonairpurifier.0 | 2021-08-17 15:09:46.903 | error | getDysonToken: Error: Request failed with status code 400
dysonairpurifier.0 | 2021-08-17 15:09:44.767 | error | getDyson2faMailError: Request failed with status code 401
dysonairpurifier.0 | 2021-08-17 15:07:46.707 | error | getDyson2faMailError: Request failed with status code 401

**Comment by Grizzelbee** [comment]
> Versionen von js-controller:3.2.16
> Admin:5.1.23

Ich will es nicht beschwören ... aber ich würde als erstes mal den js-controller updaten.
Meines Wissens nach sind im js-controller 3.3.15 diverse Apassungen für Admin 5.1.x drin. 
Will sagen: Ich vermute das Admin 5.1.x und Controller 3.2.x nicht kompatibel sind.

Und leider zeigt das "normale" Log nicht genug an. Bitte den Adapter im DEBUG-Modus ausführen.

**Comment by kkickingereder** [comment]
Danke @Grizzelbee den Adapter und deine Arbeit die da reinsteckst.

Evtl. hilft dir das weiter, eigentlich ist alles up to date bei mir.  

Node.js - v12.22.1 
NPM - 6.14.12
JS Controller - 3.3.15
Admin - v5.1.23

**Comment by Grizzelbee** [comment]
@kkickingereder 

> Danke @Grizzelbee für den Adapter überhaupt und deine Arbeit die da reinsteckst.

Was tut man nicht alles für Ruhm. ;)



> Node.js - v12.22.1
NPM - 6.14.12
JS Controller - 3.3.15
Admin - v5.1.23

Die Versionen sind alle okay - soweit ich das beurteilen kann. Sind bir mir jedenfalls auf Windows und Linux genau so. Passt also.
Das alleine kann es also nicht sein, denn bei mir funktioniert es auf beiden Plattformen.

Wir kommen also an Debug-Logs nicht vorbei.

**Comment by ManuW19** [comment]
Mit mehr als dem hier kann ich nicht dienen.... Bin etwas unerfahren ist Debug Modus gleich Expertenmodus?

2021-08-17 17:36:59.820  - info: host.homebridge stopInstance system.adapter.dysonairpurifier.0 (force=false, process=true)
--
2021-08-17 17:36:59.867  - info: dysonairpurifier.0 (2811) Got terminate signal TERMINATE_YOURSELF
2021-08-17 17:36:59.868  - info: host.homebridge stopInstance system.adapter.dysonairpurifier.0 send kill signal
2021-08-17 17:36:59.870  - info: dysonairpurifier.0 (2811) Cleaned up everything...
2021-08-17 17:36:59.872  - info: dysonairpurifier.0 (2811) terminating
2021-08-17 17:36:59.876  - info: dysonairpurifier.0 (2811) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-08-17 17:37:00.466  - info: host.homebridge instance system.adapter.dysonairpurifier.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-08-17 17:37:03.040  - info: host.homebridge instance system.adapter.dysonairpurifier.0 started with pid 5803
2021-08-17 17:37:06.168  - info:  dysonairpurifier.0 (5803) starting. Version 0.9.2 in  /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v14.17.4,  js-controller: 3.2.16
2021-08-17 17:37:06.248  - info: dysonairpurifier.0 (5803) Querying devices from dyson API.
2021-08-17 17:37:06.628  - error: dysonairpurifier.0 (5803) [main()] error: undefined, stack: undefined
2021-08-17 17:37:15.147  - info: host.homebridge "system.adapter.dysonairpurifier.0" disabled
2021-08-17 17:37:15.149  - info: host.homebridge stopInstance system.adapter.dysonairpurifier.0 (force=false, process=true)
2021-08-17 17:37:15.167  - info: dysonairpurifier.0 (5803) Got terminate signal TERMINATE_YOURSELF
2021-08-17 17:37:15.169  - info: host.homebridge stopInstance system.adapter.dysonairpurifier.0 send kill signal
2021-08-17 17:37:15.170  - info: dysonairpurifier.0 (5803) Cleaned up everything...
2021-08-17 17:37:15.172  - info: dysonairpurifier.0 (5803) terminating
2021-08-17 17:37:15.175  - info: dysonairpurifier.0 (5803) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-08-17 17:37:15.749  - info: host.homebridge instance system.adapter.dysonairpurifier.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-08-17 17:37:21.867  - info: host.homebridge "system.adapter.dysonairpurifier.0" enabled
2021-08-17 17:37:21.990  - info: host.homebridge instance system.adapter.dysonairpurifier.0 started with pid 5821
2021-08-17 17:37:25.068  - info:  dysonairpurifier.0 (5821) starting. Version 0.9.2 in  /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v14.17.4,  js-controller: 3.2.16
2021-08-17 17:37:25.161  - info: dysonairpurifier.0 (5821) Querying devices from dyson API.
2021-08-17 17:37:25.487  - error: dysonairpurifier.0 (5821) [main()] error: undefined, stack: undefined
2021-08-17 17:37:32.349  - error: dysonairpurifier.0 (5821) getDyson2faMailError: Request failed with status code 401

**Comment by Grizzelbee** [comment]
@ManuW19 

Nein - der Expertenmodus ist nicht der Debug-Modus, aber er ist die erste Station auf dem Weg dorthin.

![grafik](https://user-images.githubusercontent.com/5459426/129760259-1fff43e7-a596-4957-88d6-c0a942c25e1e.png)

1. Bei den Instanzen den Expertenmodus aktivieren
2. Den Adapter soppelt anklicken, damit der "ausrollt"
3. Den Log-Modus von Info auf Debug umstellen, indem Du auf den Stift (Editieren) klickst. 
4. Adapter neu starten lassen
5. Alle Schitte bis zum Aftreten des Fehlers durchführen
6. Debug-Log hier posten (ggf. vorher filtern - aber das kannst Du ja)

**Comment by ManuW19** [comment]
OK hier ist er:

dysonairpurifier.0 | 2021-08-17 20:33:46.757 | debug | sendTo "send" to system.adapter.admin.0 from system.adapter.dysonairpurifier.0: getDyson2faMail
-- | -- | -- | --
dysonairpurifier.0 | 2021-08-17 20:33:46.755 | error | getDyson2faMailError: Request failed with status code 401
dysonairpurifier.0 | 2021-08-17 20:33:46.355 | debug | Utils: getDyson2faMail!
dysonairpurifier.0 | 2021-08-17 20:33:46.352 | debug | OnMessage: locale: de-DE
dysonairpurifier.0 | 2021-08-17 20:33:46.350 | debug | OnMessage: country: DE
dysonairpurifier.0 | 2021-08-17 20:33:46.348 | debug | OnMessage: Mail: (hier stand die richtige E-Mail Adressse)
dysonairpurifier.0 | 2021-08-17 20:33:31.696 | error | [main()] error: undefined, stack: undefined
dysonairpurifier.0 | 2021-08-17 20:33:31.409 | info | Querying devices from dyson API.
dysonairpurifier.0 | 2021-08-17 20:33:31.328 | info | starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v14.17.4, js-controller: 3.2.16
dysonairpurifier.0 | 2021-08-17 20:33:30.887 | debug | Plugin sentry Initialize Plugin (enabled=true)
dysonairpurifier.0 | 2021-08-17 20:33:30.660 | debug | statesDB connected
dysonairpurifier.0 | 2021-08-17 20:33:30.658 | debug | States connected to redis: 127.0.0.1:9000
dysonairpurifier.0 | 2021-08-17 20:33:30.645 | debug | States create User PubSub Client
dysonairpurifier.0 | 2021-08-17 20:33:30.643 | debug | States create System PubSub Client
dysonairpurifier.0 | 2021-08-17 20:33:30.629 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
dysonairpurifier.0 | 2021-08-17 20:33:30.624 | debug | objectDB connected
dysonairpurifier.0 | 2021-08-17 20:33:30.608 | debug | Objects connected to redis: 127.0.0.1:9001
dysonairpurifier.0 | 2021-08-17 20:33:30.587 | debug | Objects client initialize lua scripts
dysonairpurifier.0 | 2021-08-17 20:33:30.584 | debug | Objects create User PubSub Client
dysonairpurifier.0 | 2021-08-17 20:33:30.582 | debug | Objects create System PubSub Client
dysonairpurifier.0 | 2021-08-17 20:33:30.578 | debug | Objects client ready ... initialize now
dysonairpurifier.0 | 2021-08-17 20:33:30.524 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
host.homebridge | 2021-08-17 20:33:28.300 | info | instance system.adapter.dysonairpurifier.0 started with pid 7591
host.homebridge | 2021-08-17 20:33:28.196 | info | "system.adapter.dysonairpurifier.0" enabled

**Comment by Grizzelbee** [comment]
@ManuW19 
Okay. Gehen wir es systematisch an:
1. Die Installation scheint okay zu sein - kein Unknown Funktion oder ähnliches. 
2. Der Adapter ist gestartet.
3. Es gibt grundsätzlich Konfig-Daten 
4. Der Klick auf den Button wird registriert und die gerufene Funktion ausgeführt
5. Der Adapter kommuniziert mit dem dyson-Server
6. Der Adapter überträgt Daten und bekommt vom dyson-Server als Antwort auf den Login-Versuch einen 401 - Unauthorized

Das bedeutet, das der Dyson Server Username, Passwort und Locale empfängt, prüft und als ungültig abweist. Dafür wird er schon irgendwelche Gründe haben.

Also noch einmal die Frage: Du hast ein aktives Dyson Konto, die Smartphone App ist installiert, läuft und kann deinen Lüfter steuern?

**Comment by kkickingereder** [comment]
Auch bei mir gleicher Fehler.
Dyson Konto funktioniert, in der App kann ich alles ohne Probleme steuern.


dysonairpurifier.0 | Zeit | debug | Nachricht
-- | -- | -- | --
dysonairpurifier.0 | 2021-08-18 16:05:03.964 | debug | sendTo "send" to system.adapter.admin.0 from system.adapter.dysonairpurifier.0: getDyson2faMail
**dysonairpurifier.0 | 2021-08-18 16:05:03.962 | error | getDyson2faMailError: Request failed with status code 401**
dysonairpurifier.0 | 2021-08-18 16:05:03.038 | debug | Utils: getDyson2faMail!
dysonairpurifier.0 | 2021-08-18 16:05:03.038 | debug | OnMessage: locale: de-DE
dysonairpurifier.0 | 2021-08-18 16:05:03.037 | debug | OnMessage: country: DE
dysonairpurifier.0 | 2021-08-18 16:05:03.037 | debug | OnMessage: Mail: klaus@kickingereder.org
dysonairpurifier.0 | 2021-08-18 16:04:59.899 | error | [main()] error: undefined, stack: undefined
dysonairpurifier.0 | 2021-08-18 16:04:59.728 | info | Querying devices from dyson API.
dysonairpurifier.0 | 2021-08-18 16:04:59.690 | info | starting. Version 0.9.2 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v12.22.1, js-controller: 3.3.15
dysonairpurifier.0 | 2021-08-18 16:04:59.537 | debug | Plugin sentry Initialize Plugin (enabled=true)

**Comment by ManuW19** [comment]
Ja ich kann ihn über die App steuern.

**Comment by Grizzelbee** [comment]
Ich vermute ehrlich gesagt, dass sich bei der Mailadresse oder dem Passwort durch Copy&Paste vorne oder hinten ein whitespace eingeschlichen hat. Der 401 Fehler spricht schon eine sehr klare Sprache - außerdem funktioniert der Adapetr ja bei fast 200 Leuten.
Deshalb habe mal ein bisschen debug-code eingebaut der das sichtbar machen kann. Gleichzeitig entferne ich ab sofort whitespaces beim Speichern der Config-Daten.

Bitte mal mit der 0.9.3 probieren. Vielleicht kommen wir der Sache näher.

**Comment by Grizzelbee** [comment]
Schaut euch bitte mal das hier an und probiert die Anleitung: https://github.com/naimo84/node-red-contrib-dyson-purelink/issues/34
Sieht so aus, als hätte dyson mal wieder etwas an seiner API geändert...

**Comment by Grizzelbee** [comment]
Okay. Things a tighen up. Seems like dyson changed it's Login method once more:
* https://github.com/Grizzelbee/ioBroker.dysonairpurifier/issues/120 (first reported occurence)
* https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/205

**Comment by kkickingereder** [comment]
Yeah ich habs geschafft !!!
Von der Dyson App (ios / Android) abmelden
Dann Adapter stoppen, Einstellungen löschen (email, PW) und neu starten
Adapter geht auf gelb, dann Einstellungen und EMail, PW, Region -> 2FA neu anfordern
An die Email wird der Einmalcode gesendet, diesen Eintragen und voila Adapter auf grün

**Comment by Grizzelbee** [comment]
@kkickingereder   Hey! :) Good to hear! And thanks for your support!

**Comment by Reventrop** [comment]
2021-08-21 07:46:46.237 - error: dysonairpurifier.0 (25878) CATCH-getDyson2faMail: [{"message":"1","name":"2","stack":"3","config":"4"},"Request failed with status code 401","Error","Error: Request failed with status code 401\n at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)\n at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)\n at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)\n at IncomingMessage.emit (events.js:326:22)\n at IncomingMessage.EventEmitter.emit (domain.js:483:12)\n at endReadableNT (_stream_readable.js:1241:12)\n at processTicksAndRejections (internal/process/task_queues.js:84:21)",{"url":"5","method":"6","data":"7","headers":"8","transformRequest":"9","transformResponse":"10","timeout":0,"xsrfCookieName":"11","xsrfHeaderName":"12","maxContentLength":-1,"maxBodyLength":-1,"httpsAgent":"13","json":true},"https://appapi.cp.dyson.com/v3/userregistration/email/userstatus?country=AT","post","{\"Email\":\"xxxxxxxxxx@yyyyyyy.zz\",\"Password\":\"***************\"}",{"Accept":"14","Content-Type":"15","User-Agent":"16","Content-Length":66},[null],[null],"XSRF-TOKEN","X-XSRF-TOKEN",{"_events":"17","_eventsCount":2,"_maxListeners":100,"defaultPort":443,"protocol":"18","options":"19","requests":"20","sockets":"21","freeSockets":"22","keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"maxTotalSockets":null,"totalSocketCount":1,"scheduling":"23","maxCachedSessions":100,"_sessionCache":"24"},"application/json, text/plain, */*","application/json","Dalvik/2.1.0 (Linux; U; Android 8.1.0; Google Build/OPM6.171019.030.E1)",{},"https:",{"ca":"25","path":null},{},{"appapi.cp.dyson.com:443::-----BEGIN CERTIFICATE-----\nMII.........

**Comment by ManuW19** [comment]
Hallo... Ich mal wieder.... Habe Version 0.9.4 installiert und mich aus der App abgemeldet. Habe auch die ID und den PIN bekommen. Habe alles gespeichert und dachte jetzt geht es. Aber die Instanz wurde nicht grün. Nochmal in den Einstellungen geschaut, alle Daten waren wieder weg. Email PW usw... Habe es ein paar Mal probiert, ist aber immer wieder gekommen. Nach den anderen Themen hier, habe ich wieder die Version 0.9.2 installiert. Hier werden alle Einstellungen gespeichert aber die Fehlermeldung 401 kommt wieder. Also nochmal die Version 0.9.4 drauf und nochmal probiert. Jetzt kommt hier mit den selben Daten auch der Fehler 401. Bin echt am verzweifeln....

**Comment by ManuW19** [comment]
Habe jetzt meinen Fehler gefunden. Da ich zu oft versucht habe, den Code anzufordern, hatte ich eine 30 Minuten Sperre drin.
Jetzt hat es bei Version 0.9.2 funktioniert. Habe die ID und Email bekommen. Auf Finish geklickt und gespeichert.
Adapter wird aber nicht grün...
Fehlermeldung ist



dysonairpurifier.1 | 2021-08-22 15:09:41.285 | error | [main()] error: undefined, stack: undefined
-- | -- | -- | --

Werte stehen aber bei den Einstellungen alle richtig drin.... Ich zweifel langsam an mir selber....

**Comment by ManuW19** [comment]
Mit Version 0.9.5 hat es nun endlich geklappt. Instanz ist auf grün und Lüfter werden angezeigt. Danke für deine Hilfe!

**Comment by Grizzelbee** [comment]
@ManuW19 
> Mit Version 0.9.5 hat es nun endlich geklappt. Instanz ist auf grün und Lüfter werden angezeigt. Danke für deine Hilfe!

Freut mich zu hören, dass es nun  endlich klappt. Obschon ich sagen muss, das mir nach wie vor nicht so richtig klar ist, wo genau es geklemmt hat. Aber den Adapter hat die Aktion auf jeden Fall besser gemacht. Dafür ein: 👍
