### ISSUE TITLE
Probleme mit neuer Version 2.1.2

### ISSUE THREAD

**Issue by viper4gh** [Grizzelbee/ioBroker.dysonairpurifier#147]
Hi,
es scheint wieder das Problem mit der Host-Adresse zurück zu sein, was wir vor längerer Zeit schon einmal hatten.
Ich hatte auf die 2.1.2 aktualisiert, den Objekt-Baum gelöscht, Instanz gestartet. 
Dann versucht er den kryptischen Namen als Hostnamen zu erreichen, was bei mir wegen eigenem DNS-Server nicht funktioniert.
Habe dann die IP-Adresse bei der Host-Adresse angegeben und die Instanz neu gestartet und dann kommt im Log:
`No host address given. Trying to connect to the device with it's default hostname ...`
Er ignoriert scheinbar diesen Hostaddress Eintrag aus dem Objektbaum.
Es hat bei mir erst funktioniert als ich in meinem DNS-Server diesen kryptischen Namen hinterlegt habe.

**Comment by Grizzelbee** [comment]
Hi @viper4gh ,

also die #149 war mir einfach nur noch so nebenher aufgefallen und ich dachte ich erwähne es selbst damit nicht womöglich noch ein Issue dazu aufgemacht wird.

Das komische Verhalten des MainPower kann ich jetzt bestätigen:
* https://github.com/Grizzelbee/ioBroker.dysonairpurifier/issues/150
Ich gucke mir das an.

**Comment by Grizzelbee** [comment]
@viper4gh Teste doch bitte mal die V2.1.3. Die sollte alle deine Probleme mit der V2.1.2 beheben.

**Comment by viper4gh** [comment]
Leider bekomme ich die 2.1.3 nicht installiert.
Habe es über das iobroker WebUI aus GitHub probiert, dann mit der benutzerdefinieten Option, wo man die URL vom Release File angibt. Und dann habe ich es noch über Konsole mit "sudo npm install iobroker.dysonairpurifier" probiert.
Er bleibt immer auf der alten Version. Keine Ahnung, was ich falsch mache.

**Comment by viper4gh** [comment]
@Grizzelbee 

Ich habe jetzt den gesamten Adapter gelöscht.
Im stable und latest repo bekomme ich weiterhin nur die 2.1.2 angezeigt.
Wenn ich es von github installiere, wird folgendes Log erzeugt:

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'Grizzelbee/ioBroker.dysonairpurifier',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.1
4 verbose npm-session 3482d309e8d494dd
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose prepareGitDep undefined: installing devDeps and running prepare script.
8 silly fetchPackageMetaData error for github:Grizzelbee/ioBroker.dysonairpurifier premature close
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 4123ms
11 verbose stack Error: premature close
11 verbose stack     at PassThrough.onclose (/usr/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
11 verbose stack     at PassThrough.emit (events.js:412:35)
11 verbose stack     at emitCloseNT (internal/streams/destroy.js:87:10)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:81:21)
12 verbose cwd /opt/iobroker
13 verbose Linux 5.4.0-88-generic
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "Grizzelbee/ioBroker.dysonairpurifier" "--loglevel" "error" "--prefix" "/opt/iobroker"
15 verbose node v14.18.1
16 verbose npm  v6.14.15
17 error premature close
18 verbose exit [ 1, true ]
`

**Comment by viper4gh** [comment]
Da ich den Adapter komplett gelöscht habe, scheitere ich jetzt schon beim Einrichten von 2FA.
Die alten Daten funktionieren nicht mehr und wenn ich 2FA erneut anstoße, kommt:

> Received error: [Error: Request failed with status code 401] from dyson API.
