### ISSUE TITLE
Install not possible

### ISSUE THREAD

**Issue by libertyx82** [Grizzelbee/ioBroker.dysonairpurifier#88]
I have tried to Install the Adapter but it wont work

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'Grizzelbee/ioBroker.dysonairpurifier#master',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v12.22.0
4 verbose npm-session e54f7adef000d063
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose prepareGitDep github:Grizzelbee/ioBroker.dysonairpurifier#master: installing devDeps and running prepare script.
8 silly fetchPackageMetaData error for github:Grizzelbee/ioBroker.dysonairpurifier#master premature close
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 2424ms
11 verbose stack Error: premature close
11 verbose stack     at PassThrough.onclose (/usr/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
11 verbose stack     at PassThrough.emit (events.js:326:22)
11 verbose stack     at emitCloseNT (internal/streams/destroy.js:69:8)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:83:21)
12 verbose cwd /opt/iobroker
13 verbose Linux 4.19.0-16-amd64
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "Grizzelbee/ioBroker.dysonairpurifier#master" "--loglevel" "error" "--prefix" "/opt/iobroker"
15 verbose node v12.22.0
16 verbose npm  v6.14.11
17 error premature close
18 verbose exit [ 1, true ]
```

**Comment by Grizzelbee** [comment]
How did you try to install the adapter?
As far as I know at least the installation via Adapters-Tab in ioBroker and githib-icon on top of the page should work.

**Comment by libertyx82** [comment]
I have tried both, over the Adapters Tab "from github" and "from URL"

![Screenshot 2021-04-04 111655](https://user-images.githubusercontent.com/22996350/113504338-c96c7400-9537-11eb-90f4-2c3e2ac6e248.jpg)
![Screenshot 2021-04-04 111722](https://user-images.githubusercontent.com/22996350/113504339-ca050a80-9537-11eb-999d-aeab7e262e7f.jpg)

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'Grizzelbee/ioBroker.dysonairpurifier#master',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v12.22.0
4 verbose npm-session aeae5da2297c1928
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose prepareGitDep github:Grizzelbee/ioBroker.dysonairpurifier#master: installing devDeps and running prepare script.
8 silly fetchPackageMetaData error for github:Grizzelbee/ioBroker.dysonairpurifier#master premature close
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 2975ms
11 verbose stack Error: premature close
11 verbose stack     at PassThrough.onclose (/usr/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
11 verbose stack     at PassThrough.emit (events.js:326:22)
11 verbose stack     at emitCloseNT (internal/streams/destroy.js:69:8)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:83:21)
12 verbose cwd /opt/iobroker
13 verbose Linux 4.19.0-16-amd64
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "Grizzelbee/ioBroker.dysonairpurifier#master" "--loglevel" "error" "--prefix" "/opt/iobroker"
15 verbose node v12.22.0
16 verbose npm  v6.14.11
17 error premature close
18 verbose exit [ 1, true ]
```

**Comment by Grizzelbee** [comment]
Hmmm. Strange. There haven't been any installation issues in the beginning, and since some short time you are the second one complaining on installation issues. I'll need to do some research on that.

This line:
> 14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "Grizzelbee/ioBroker.dysonairpurifier#master" "--loglevel" "error" "--prefix" "/opt/iobroker"

looks strange to me. It tries to install via npm using a part of the git-URL - which can't work.

But for now please try to install via command line using: `npm install iobroker.dysonairpurifier` in your ioBroker folder (e.g. /opt/iobroker) and read [This Issue #75](https://github.com/Grizzelbee/ioBroker.dysonairpurifier/issues/75) before.

**Comment by Grizzelbee** [comment]
This Issue is a duplicate to #80

**Comment by Grizzelbee** [comment]
Should be solved with 0.8.2.
Please give it a try and close this issue if it works.
